# <font color='navygray'>MF013 Análisis de inversión:  Introducción a Algotrading</font>
Por Carlos Crespo Elizondo, MSF<br>
Clase del 07-10-20

## <font color='navygray'>Guardar más información en una variable</font>


### <font color='navygray'>Listas</font>


Una *__lista__* es colección o agrupación de elementos (items) *en un orden en patricular*.  Pueden incluir texto (str), números (int/float), otra lista, etc.<br><br>
En Python, las *__listas__* se definen con corchetes __[ ]__ y los elementos se separan entre si con una coma.

In [1]:
lista_precios = [10, 10.1, 10.5, 9.8]

Las listas empeizan a enumerarse a partir de cero (index 0), por lo tanto el segundo elemento de la lista está en el espacio 1 y así susesivamente para cada uno de los elementos de la lista.

#### <font color='gray'>Accesar a un elemento de la lista</font>


Para accesar a *__un__* valor o elemento de una lista se utiliza el *__nombre de la lista__* y enseguida se habre unos corchetes *__[ ]__* y adentro de los corchetes se pone el número de index de la lista.<br><br>
Por ejemplo el valor *__10.1__* de la lista anterior ocupa el **index** número uno:

In [2]:
lista_precios[1]

10.1

También se puede accesar a los valores del final hacia el inicio.  En este caso la enumeración cambia y empieza de -1 en adelante.  El -1 represente el último valor, -2 el penúltimo y así hasta llegar al primer valor de la lista.

In [3]:
lista_precios[-1]

9.8

#### <font color='gray'>Utilizar elementos de la lista</font>


Para utilizar un elemento de la lista lo seleccionamos y luego le asignamos alguna operación.<br><br>
Por ejemplo vamor a multiplicar el valor de 10.5 (index = 2) por 3

In [4]:
lista_precios[2] * 3

31.5

también podemos asignar el valor de un elemento de la lista a una variable.  Por ejemplo, ahora escogemos el último valor de la lista, le asignamos la varible *__precio_ultimo__* y lo elevamos al cuadrado.  Recordar que para elevar al cuadrado, se utiliza dos veces el símbolo *:

In [5]:
precio_ultimo = lista_precios[-1]
print('El último precio de la lista es: '+ str(precio_ultimo))
precio_ultimo**2

El último precio de la lista es: 9.8


96.04000000000002

#### <font color='gray'>Modificar elementos de la lista</font>


Modificar el valor de una lista es muy sencillo, solo se necesita asignarle el nuevo valor al espacio donde se quiere actutalizar.  El valor original se borra.<br><br>
Recordemos los valores de la lista:

In [6]:
lista_precios

[10, 10.1, 10.5, 9.8]

Ahora vamos a modificar el último valor con index 3

In [7]:
lista_precios[3] = 10.55
print(lista_precios)

[10, 10.1, 10.5, 10.55]


#### <font color='gray'>Agregar elemento a una lista</font>



Existen dos maneras de agregar valores a una lista.  La primer consiste en utilizar el método *__.append( )__*.  Y la segunda es utilizar el método *__insert( )__*.

##### <font color='gray'>Agregar elemento a la lista APPEND</font>


.append( ), asigna el valor al final de la lista!<br><br>
Vamos a asignar el valor 9.99 al final de *__lista_precios__*:

In [8]:
lista_precios.append(9.99)
lista_precios

[10, 10.1, 10.5, 10.55, 9.99]

##### <font color='gray'>Agregar elemento a la lista INSERT</font>


En algunas ocasiones es necesario ingresar un valor nuevo en alguna punto específico de la lista.  Para estos casos se usa .insert(ubicación index, valor agregar):

In [9]:
lista_precios.insert(2, 5.2)

In [10]:
lista_precios

[10, 10.1, 5.2, 10.5, 10.55, 9.99]

#### <font color='gray'>Eliminar elemento de la lista</font>

Existen tres maneras de eliminar un valor de una lista:
1. Función *__del__*:  Elimina el valor en función a su ubicación en el index
1. Método *__remove__*:  Elimina el valor en función precisamente del valor
1. Método *__pop__*:  Elimina el valor PERO lo asinga a una variable

##### <font color='gray'>Eliminar elemento de la lista DEL</font>


In [11]:
print(lista_precios)
del lista_precios[0]
lista_precios

[10, 10.1, 5.2, 10.5, 10.55, 9.99]


[10.1, 5.2, 10.5, 10.55, 9.99]

#### <font color='gray'>Eliminar elemento de la lista REMOVE</font>


In [12]:
print(lista_precios)
lista_precios.remove(5.2)
lista_precios

[10.1, 5.2, 10.5, 10.55, 9.99]


[10.1, 10.5, 10.55, 9.99]

#### <font color='gray'>Eliminar elemento de la lista POP</font>


In [13]:
print(lista_precios)
valor = lista_precios.pop(-2)
print(lista_precios)
print(valor)

[10.1, 10.5, 10.55, 9.99]
[10.1, 10.5, 9.99]
10.55


#### <font color='gray'>Ordenar una lista: A--->Z / Z--->A</font>


Las listas se pueden ordenar de manera asendente y desendiente.  El orden puede ser permanente o momentaneo.

##### <font color='gray'>Arreglar la lista de manera asendente permanentemente SORT </font>


Para ordenar una lista de manera permanente se utiliza el método *__.sort( )__*.  El método tiene el parámetro (se puede ver como un setting) *__reverse__*.  Por default, reverse = False y no necesitas definirlo si se quiere un orden asentente.

In [14]:
print('Lista antes de ordenarla:')
print(lista_precios)

Lista antes de ordenarla:
[10.1, 10.5, 9.99]


In [15]:

print('Lista ordenada:')
lista_precios.sort()
print(lista_precios)

Lista ordenada:
[9.99, 10.1, 10.5]


In [16]:
lista_texto = ['b','a','e','d']
lista_texto.sort()
lista_texto

['a', 'b', 'd', 'e']

##### <font color='gray'>Arreglar la lista de manera desendiente permanentemente SORT</font>


Cuando se desea un orden desendiente sí se necesita especificar reverse como verdadero:

In [17]:
lista_precios.sort(reverse=True)

In [18]:
lista_precios

[10.5, 10.1, 9.99]

##### <font color='gray'>Arreglar la lista de manera desendiente momentaneamente SORTED</font>


Aun y que no vamos a ver un sort momentaneo en la clase, aprovechamos para ver como se realiza:

In [19]:
print(sorted(lista_precios))

[9.99, 10.1, 10.5]


#### <font color='gray'>Rebanar (seccionar) la lista</font>


Para seleccionar un rango de elementos de una lista, debemos de utilizar el concepto que en Python se llama _slice_ / _slicing_, rebanar en español.<br><br>
Para hacer un slice, se necesita definir el index del primer y último elemento.  Es importante recordar que Python no toma encuenta el último elemento, sino uno previo al último.  De tal manera que si quieres seleccionar los primeros tres elementos de una lista se tiene que pedir del 0 al 3, para que Python regrese los elementos index 0, 1 y 2.<br><br>
Con todos los movimientos anteriores la lista se acortó, por lo que la voy a volver a escribir:

In [20]:
lista_precios = [10.55, 10.15, 9.99, 10.55, 10.15, 9.99]

Vamos a seleccionar los valores index 1, 2 y 3 (10.15, 9.99, 10.55):

In [21]:
lista_precios[1:4]

[10.15, 9.99, 10.55]

Para seleccionar los valores index 0 al 2 (10.55, 10.15, 9.99):

In [22]:
lista_precios[0:3]

[10.55, 10.15, 9.99]

El slice anterior empieza en el index 0, pues estamos seleccionando el primer valor de la lista.  Como es el inicio de la lista, podemos omitir definir el index 0:

In [23]:
lista_precios[:3]

[10.55, 10.15, 9.99]

De la misma manera, también se puede omitir el último elemento de la lista!  Por ejemplo, el siguiente slice seleccionan los valores del index 3, 4 y 5:

In [24]:
lista_precios[3:6]

[10.55, 10.15, 9.99]

In [25]:
lista_precios[3:]

[10.55, 10.15, 9.99]

Por último y esto no lo vimos en clases...  que pasa si multiplicamos una lista por 2?:

In [26]:
lista_precios * 2

[10.55,
 10.15,
 9.99,
 10.55,
 10.15,
 9.99,
 10.55,
 10.15,
 9.99,
 10.55,
 10.15,
 9.99]

simplemente duplicó la lista

### <font color='navygray'>Tuplas</font>


Las tuplas son una especie de listas de Python que una vez declaradas no se pueden editar. Las tuplas se declaran utilizando ( ) en lugar de [ ]. Toda la lógica de las listas, aplica para las tuplas, excepto modificar la misma.

In [27]:
tupla_precios = (9.99, 9.99, 10.15)

In [28]:
tupla_precios[:2]

(9.99, 9.99)

En el siguiente renglon se va a generar un error al intentar asignarle un valor al index 0:

In [29]:
tupla_precios[0] = 10

TypeError: 'tuple' object does not support item assignment

#### <font color='gray'>Modificar tupla rescribiendola</font>


La única manera de modificar una tupla es volviéndola a definir (borrar y escribir):

In [30]:
print(tupla_precios)
tupla_precios = (9.99, 9.99, 10.15, 10)
tupla_precios

(9.99, 9.99, 10.15)


(9.99, 9.99, 10.15, 10)

### <font color='navygray'>Diccionarios</font>


En Python, los diccionarios son una colección de datos relacionados por una *__llave__* y un *__valor__*.  Se definen con *__"{ }"__*, y pueden de ser de cualquier tamaño. A diferencia de las listas, los diccionarios no tienen un orden específico ya que todo se relaciona por el nombre de la llave<br><br>. Pueden estar formados por diccionarios adentro del diccionario, listas, etc.<br><br>

#### <font color='gray'>Accesar a un valor del diccionario</font>


#### <font color='gray'>Agregar elementos a un diccionario ya construido</font>


#### <font color='gray'>Agregar elementos a un diccionario ya construido</font>


#### <font color='gray'>Modificar un valor de un diccionario</font>


#### <font color='gray'>Eliminar llave/valor de un diccionario POP</font>


## <font color='navygray'>For Loop</font>


#### <font color='gray'>En listas</font>


#### <font color='gray'>En diccionarios</font>
